countries_database = [
    {'name': 'world', 'code': 0},
    {'name': 'Africa', 'type': 'continent', 'code': 1},
    {'name': 'South America', 'type': 'continent', 'code': 2},
    {'name': 'North America', 'type': 'continent', 'code': 3},
    {'name': 'Central America', 'type': 'continent', 'code': 4},
    {'name': 'Caribbean', 'type': 'continent', 'code': 5},
    {'name': 'Asia', 'type': 'continent', 'code': 6},
    {'name': 'Europe', 'type': 'continent', 'code': 7},
    {'name': 'Oceania', 'type': 'continent', 'code': 8},
    {'name': 'Middle East', 'type': 'continent', 'code': 600},
    {'name': 'Afghanistan', 'continent': 'Asia', 'type': 'country', 'code': 9},
    {'name': 'Aland', 'continent': 'Europe', 'type': 'country', 'code': 10},
    {'name': 'Albania', 'continent': 'Europe', 'type': 'country', 'code': 11},
    {'name': 'Algeria', 'continent': 'Africa', 'type': 'country', 'code': 12},
    {'name': 'American Samoa', 'continent': 'Oceania', 'type': 'country', 'code': 13},
    {'name': 'Andorra', 'continent': 'Europe', 'type': 'country', 'code': 14},
    {'name': 'Angola', 'continent': 'Africa', 'type': 'country', 'code': 15},
    {'name': 'Anguilla', 'continent': 'Caribbean', 'type': 'country', 'code': 16},
    {'name': 'Antarctica', 'continent': 'Antarctica', 'type': 'country', 'code': 17},
    {'name': 'Antigua and Barbuda', 'continent': 'Caribbean', 'type': 'country', 'code': 18},
    {'name': 'Argentina', 'continent': 'South America', 'type': 'country', 'code': 19},
    {'name': 'Armenia', 'continent': 'Asia', 'type': 'country', 'code': 20},
    {'name': 'Aruba', 'continent': 'Caribbean', 'type': 'country', 'code': 21},
    {'name': 'Australia', 'continent': 'Oceania', 'type': 'country', 'code': 22},
    {'name': 'Austria', 'continent': 'Europe', 'type': 'country', 'code': 23},
    {'name': 'Azerbaijan', 'continent': 'Asia', 'type': 'country', 'code': 24},
    {'name': 'Bahamas', 'continent': 'Caribbean', 'type': 'country', 'code': 25},
    {'name': 'Bahrain', 'continent': 'Asia', 'type': 'country', 'code': 26},
    {'name': 'Bangladesh', 'continent': 'Asia', 'type': 'country', 'code': 27},
    {'name': 'Barbados', 'continent': 'Caribbean', 'type': 'country', 'code': 28},
    {'name': 'Belarus', 'continent': 'Europe', 'type': 'country', 'code': 29},
    {'name': 'Belgium', 'continent': 'Europe', 'type': 'country', 'code': 30},
    {'name': 'Belize', 'continent': 'Central America', 'type': 'country', 'code': 31},
    {'name': 'Benin', 'continent': 'Africa', 'type': 'country', 'code': 32},
    {'name': 'Bermuda', 'continent': 'North America', 'type': 'country', 'code': 33},
    {'name': 'Bhutan', 'continent': 'Asia', 'type': 'country', 'code': 34},
    {'name': 'Bolivia', 'continent': 'South America', 'type': 'country', 'code': 35},
    {'name': 'Bonaire', 'continent': 'Caribbean', 'type': 'country', 'code': 36},
    {'name': 'Bosnia and Herzegovina', 'continent': 'Europe', 'type': 'country', 'code': 37},
    {'name': 'Botswana', 'continent': 'Africa', 'type': 'country', 'code': 38},
    {'name': 'Bouvet Island', 'continent': 'Antarctica', 'type': 'country', 'code': 39},
    {'name': 'Brazil', 'continent': 'South America', 'type': 'country', 'code': 40},
    {'name': 'British Indian Ocean Territory', 'continent': 'Asia', 'type': 'country', 'code': 41},
    {'name': 'United States Minor Outlying Islands', 'continent': 'North America', 'type': 'country', 'code': 42},
    {'name': 'British Virgin Islands', 'continent': 'Caribbean', 'type': 'country', 'code': 43},
    {'name': 'U.S. Virgin Islands', 'continent': 'Caribbean', 'type': 'country', 'code': 44},
    {'name': 'Brunei', 'continent': 'Asia', 'type': 'country', 'code': 45},
    {'name': 'Bulgaria', 'continent': 'Europe', 'type': 'country', 'code': 46},
    {'name': 'Burkina Faso', 'continent': 'Africa', 'type': 'country', 'code': 47},
    {'name': 'Burundi', 'continent': 'Africa', 'type': 'country', 'code': 48},
    {'name': 'Cambodia', 'continent': 'Asia', 'type': 'country', 'code': 49},
    {'name': 'Cameroon', 'continent': 'Africa', 'type': 'country', 'code': 50},
    {'name': 'Canada', 'continent': 'North America', 'type': 'country', 'code': 51},
    {'name': 'Cape Verde', 'continent': 'Africa', 'type': 'country', 'code': 52},
    {'name': 'Cayman Islands', 'continent': 'Caribbean', 'type': 'country', 'code': 53},
    {'name': 'Central African Republic', 'continent': 'Africa', 'type': 'country', 'code': 54},
    {'name': 'Chad', 'continent': 'Africa', 'type': 'country', 'code': 55},
    {'name': 'Chile', 'continent': 'South America', 'type': 'country', 'code': 56},
    {'name': 'China', 'continent': 'Asia', 'type': 'country', 'code': 57},
    {'name': 'Christmas Island', 'continent': 'Asia', 'type': 'country', 'code': 58},
    {'name': 'Cocos Islands', 'continent': 'Asia', 'type': 'country', 'code': 59},
    {'name': 'Colombia', 'continent': 'South America', 'type': 'country', 'code': 60},
    {'name': 'Comoros', 'continent': 'Africa', 'type': 'country', 'code': 61},
    {'name': 'Republic of the Congo', 'continent': 'Africa', 'type': 'country', 'code': 62},
    {'name': 'Democratic Republic of the Congo', 'continent': 'Africa', 'type': 'country', 'code': 63},
    {'name': 'Cook Islands', 'continent': 'Oceania', 'type': 'country', 'code': 64},
    {'name': 'Costa Rica', 'continent': 'Central America', 'type': 'country', 'code': 65},
    {'name': 'Croatia', 'continent': 'Europe', 'type': 'country', 'code': 66},
    {'name': 'Cuba', 'continent': 'Caribbean', 'type': 'country', 'code': 67},
    {'name': 'Curacao', 'continent': 'Caribbean', 'type': 'country', 'code': 68},
    {'name': 'Cyprus', 'continent': 'Europe', 'type': 'country', 'code': 69},
    {'name': 'Czech Republic', 'continent': 'Europe', 'type': 'country', 'code': 70},
    {'name': 'Denmark', 'continent': 'Europe', 'type': 'country', 'code': 71},
    {'name': 'Djibouti', 'continent': 'Africa', 'type': 'country', 'code': 72},
    {'name': 'Dominica', 'continent': 'Caribbean', 'type': 'country', 'code': 73},
    {'name': 'Dominican Republic', 'continent': 'Caribbean', 'type': 'country', 'code': 74},
    {'name': 'Ecuador', 'continent': 'South America', 'type': 'country', 'code': 75},
    {'name': 'Egypt', 'continent': 'Africa', 'type': 'country', 'code': 76},
    {'name': 'El Salvador', 'continent': 'Central America', 'type': 'country', 'code': 77},
    {'name': 'Equatorial Guinea', 'continent': 'Africa', 'type': 'country', 'code': 78},
    {'name': 'Eritrea', 'continent': 'Africa', 'type': 'country', 'code': 79},
    {'name': 'Estonia', 'continent': 'Europe', 'type': 'country', 'code': 80},
    {'name': 'Ethiopia', 'continent': 'Africa', 'type': 'country', 'code': 81},
    {'name': 'Falkland Islands', 'continent': 'South America', 'type': 'country', 'code': 82},
    {'name': 'Faroe Islands', 'continent': 'Europe', 'type': 'country', 'code': 83},
    {'name': 'Fiji', 'continent': 'Oceania', 'type': 'country', 'code': 84},
    {'name': 'Finland', 'continent': 'Europe', 'type': 'country', 'code': 85},
    {'name': 'France', 'continent': 'Europe', 'type': 'country', 'code': 86},
    {'name': 'French Guiana', 'continent': 'South America', 'type': 'country', 'code': 87},
    {'name': 'French Polynesia', 'continent': 'Oceania', 'type': 'country', 'code': 88},
    {'name': 'French Southern Territories', 'continent': 'Antarctica', 'type': 'country', 'code': 89},
    {'name': 'Gabon', 'continent': 'Africa', 'type': 'country', 'code': 90},
    {'name': 'Gambia', 'continent': 'Africa', 'type': 'country', 'code': 91},
    {'name': 'Georgia', 'continent': 'Asia', 'type': 'country', 'code': 92},
    {'name': 'Germany', 'continent': 'Europe', 'type': 'country', 'code': 93},
    {'name': 'Ghana', 'continent': 'Africa', 'type': 'country', 'code': 94},
    {'name': 'Gibraltar', 'continent': 'Europe', 'type': 'country', 'code': 95},
    {'name': 'Greece', 'continent': 'Europe', 'type': 'country', 'code': 96},
    {'name': 'Greenland', 'continent': 'North America', 'type': 'country', 'code': 97},
    {'name': 'Grenada', 'continent': 'Caribbean', 'type': 'country', 'code': 98},
    {'name': 'Guadeloupe', 'continent': 'Caribbean', 'type': 'country', 'code': 99},
    {'name': 'Guam', 'continent': 'Oceania', 'type': 'country', 'code': 100},
    {'name': 'Guatemala', 'continent': 'Central America', 'type': 'country', 'code': 101},
    {'name': 'Guernsey', 'continent': 'Europe', 'type': 'country', 'code': 102},
    {'name': 'Guinea', 'continent': 'Africa', 'type': 'country', 'code': 103},
    {'name': 'Guinea-Bissau', 'continent': 'Africa', 'type': 'country', 'code': 104},
    {'name': 'Guyana', 'continent': 'South America', 'type': 'country', 'code': 105},
    {'name': 'Haiti', 'continent': 'Caribbean', 'type': 'country', 'code': 106},
    {'name': 'Heard Island and McDonald Islands', 'continent': 'Antarctica', 'type': 'country', 'code': 107},
    {'name': 'Vatican City', 'continent': 'Europe', 'type': 'country', 'code': 108},
    {'name': 'Honduras', 'continent': 'Central America', 'type': 'country', 'code': 109},
    {'name': 'Hong Kong', 'continent': 'Asia', 'type': 'country', 'code': 110},
    {'name': 'Hungary', 'continent': 'Europe', 'type': 'country', 'code': 111},
    {'name': 'Iceland', 'continent': 'Europe', 'type': 'country', 'code': 112},
    {'name': 'India', 'continent': 'Asia', 'type': 'country', 'code': 113},
    {'name': 'Indonesia', 'continent': 'Asia', 'type': 'country', 'code': 114},
    {'name': 'Ivory Coast', 'continent': 'Africa', 'type': 'country', 'code': 115},
    {'name': 'Iran', 'continent': 'Asia', 'type': 'country', 'code': 116},
    {'name': 'Iraq', 'continent': 'Asia', 'type': 'country', 'code': 117},
    {'name': 'Ireland', 'continent': 'Europe', 'type': 'country', 'code': 118},
    {'name': 'Isle of Man', 'continent': 'Europe', 'type': 'country', 'code': 119},
    {'name': 'Israel', 'continent': 'Asia', 'type': 'country', 'code': 120},
    {'name': 'Italy', 'continent': 'Europe', 'type': 'country', 'code': 121},
    {'name': 'Jamaica', 'continent': 'Caribbean', 'type': 'country', 'code': 122},
    {'name': 'Japan', 'continent': 'Asia', 'type': 'country', 'code': 123},
    {'name': 'Jersey', 'continent': 'Europe', 'type': 'country', 'code': 124},
    {'name': 'Jordan', 'continent': 'Asia', 'type': 'country', 'code': 125},
    {'name': 'Kazakhstan', 'continent': 'Asia', 'type': 'country', 'code': 126},
    {'name': 'Kenya', 'continent': 'Africa', 'type': 'country', 'code': 127},
    {'name': 'Kiribati', 'continent': 'Oceania', 'type': 'country', 'code': 128},
    {'name': 'Kuwait', 'continent': 'Asia', 'type': 'country', 'code': 129},
    {'name': 'Kyrgyzstan', 'continent': 'Asia', 'type': 'country', 'code': 130},
    {'name': 'Laos', 'continent': 'Asia', 'type': 'country', 'code': 131},
    {'name': 'Latvia', 'continent': 'Europe', 'type': 'country', 'code': 132},
    {'name': 'Lebanon', 'continent': 'Asia', 'type': 'country', 'code': 133},
    {'name': 'Lesotho', 'continent': 'Africa', 'type': 'country', 'code': 134},
    {'name': 'Liberia', 'continent': 'Africa', 'type': 'country', 'code': 135},
    {'name': 'Libya', 'continent': 'Africa', 'type': 'country', 'code': 136},
    {'name': 'Liechtenstein', 'continent': 'Europe', 'type': 'country', 'code': 137},
    {'name': 'Lithuania', 'continent': 'Europe', 'type': 'country', 'code': 138},
    {'name': 'Luxembourg', 'continent': 'Europe', 'type': 'country', 'code': 139},
    {'name': 'Macau', 'continent': 'Asia', 'type': 'country', 'code': 140},
    {'name': 'North Macedonia', 'continent': 'Europe', 'type': 'country', 'code': 141},
    {'name': 'Madagascar', 'continent': 'Africa', 'type': 'country', 'code': 142},
    {'name': 'Malawi', 'continent': 'Africa', 'type': 'country', 'code': 143},
    {'name': 'Malaysia', 'continent': 'Asia', 'type': 'country', 'code': 144},
    {'name': 'Maldives', 'continent': 'Asia', 'type': 'country', 'code': 145},
    {'name': 'Mali', 'continent': 'Africa', 'type': 'country', 'code': 146},
    {'name': 'Malta', 'continent': 'Europe', 'type': 'country', 'code': 147},
    {'name': 'Marshall Islands', 'continent': 'Oceania', 'type': 'country', 'code': 148},
    {'name': 'Martinique', 'continent': 'Caribbean', 'type': 'country', 'code': 149},
    {'name': 'Mauritania', 'continent': 'Africa', 'type': 'country', 'code': 150},
    {'name': 'Mauritius', 'continent': 'Africa', 'type': 'country', 'code': 151},
    {'name': 'Mayotte', 'continent': 'Africa', 'type': 'country', 'code': 152},
    {'name': 'Mexico', 'continent': 'Central America', 'type': 'country', 'code': 153},
    {'name': 'Micronesia', 'continent': 'Oceania', 'type': 'country', 'code': 154},
    {'name': 'Moldova', 'continent': 'Europe', 'type': 'country', 'code': 155},
    {'name': 'Monaco', 'continent': 'Europe', 'type': 'country', 'code': 156},
    {'name': 'Mongolia', 'continent': 'Asia', 'type': 'country', 'code': 157},
    {'name': 'Montenegro', 'continent': 'Europe', 'type': 'country', 'code': 158},
    {'name': 'Montserrat', 'continent': 'Caribbean', 'type': 'country', 'code': 159},
    {'name': 'Morocco', 'continent': 'Africa', 'type': 'country', 'code': 160},
    {'name': 'Mozambique', 'continent': 'Africa', 'type': 'country', 'code': 161},
    {'name': 'Myanmar', 'continent': 'Asia', 'type': 'country', 'code': 162},
    {'name': 'Namibia', 'continent': 'Africa', 'type': 'country', 'code': 163},
    {'name': 'Nauru', 'continent': 'Oceania', 'type': 'country', 'code': 164},
    {'name': 'Nepal', 'continent': 'Asia', 'type': 'country', 'code': 165},
    {'name': 'Netherlands', 'continent': 'Europe', 'type': 'country', 'code': 166},
    {'name': 'New Caledonia', 'continent': 'Oceania', 'type': 'country', 'code': 167},
    {'name': 'New Zealand', 'continent': 'Oceania', 'type': 'country', 'code': 168},
    {'name': 'Nicaragua', 'continent': 'Central America', 'type': 'country', 'code': 169},
    {'name': 'Niger', 'continent': 'Africa', 'type': 'country', 'code': 170},
    {'name': 'Nigeria', 'continent': 'Africa', 'type': 'country', 'code': 171},
    {'name': 'Niue', 'continent': 'Oceania', 'type': 'country', 'code': 172},
    {'name': 'Norfolk Island', 'continent': 'Oceania', 'type': 'country', 'code': 173},
    {'name': 'North Korea', 'continent': 'Asia', 'type': 'country', 'code': 174},
    {'name': 'Northern Mariana Islands', 'continent': 'Oceania', 'type': 'country', 'code': 175},
    {'name': 'Norway', 'continent': 'Europe', 'type': 'country', 'code': 176},
    {'name': 'Oman', 'continent': 'Asia', 'type': 'country', 'code': 177},
    {'name': 'Pakistan', 'continent': 'Asia', 'type': 'country', 'code': 178},
    {'name': 'Palau', 'continent': 'Oceania', 'type': 'country', 'code': 179},
    {'name': 'Palestine', 'continent': 'Asia', 'type': 'country', 'code': 180},
    {'name': 'Panama', 'continent': 'Central America', 'type': 'country', 'code': 181},
    {'name': 'Papua New Guinea', 'continent': 'Oceania', 'type': 'country', 'code': 182},
    {'name': 'Paraguay', 'continent': 'South America', 'type': 'country', 'code': 183},
    {'name': 'Peru', 'continent': 'South America', 'type': 'country', 'code': 184},
    {'name': 'Philippines', 'continent': 'Asia', 'type': 'country', 'code': 185},
    {'name': 'Pitcairn Islands', 'continent': 'Oceania', 'type': 'country', 'code': 186},
    {'name': 'Poland', 'continent': 'Europe', 'type': 'country', 'code': 187},
    {'name': 'Portugal', 'continent': 'Europe', 'type': 'country', 'code': 188},
    {'name': 'Puerto Rico', 'continent': 'Caribbean', 'type': 'country', 'code': 189},
    {'name': 'Qatar', 'continent': 'Asia', 'type': 'country', 'code': 190},
    {'name': 'Kosovo', 'continent': 'Europe', 'type': 'country', 'code': 191},
    {'name': 'Reunion', 'continent': 'Africa', 'type': 'country', 'code': 192},
    {'name': 'Romania', 'continent': 'Europe', 'type': 'country', 'code': 193},
    {'name': 'Russia', 'continent': 'Europe', 'type': 'country', 'code': 194},
    {'name': 'Rwanda', 'continent': 'Africa', 'type': 'country', 'code': 195},
    {'name': 'Saint Barthelemy', 'continent': 'Caribbean', 'type': 'country', 'code': 196},
    {'name': 'Saint Helena', 'continent': 'Africa', 'type': 'country', 'code': 197},
    {'name': 'St. Kitts and Nevis', 'continent': 'Caribbean', 'type': 'country', 'code': 198},
    {'name': 'St. Lucia', 'continent': 'Caribbean', 'type': 'country', 'code': 199},
    {'name': 'Saint Martin', 'continent': 'Caribbean', 'type': 'country', 'code': 200},
    {'name': 'Saint Pierre and Miquelon', 'continent': 'Northern America', 'type': 'country', 'code': 201},
    {'name': 'St. Vincent and Grenadines', 'continent': 'Caribbean', 'type': 'country', 'code': 202},
    {'name': 'Samoa', 'continent': 'Oceania', 'type': 'country', 'code': 203},
    {'name': 'San Marino', 'continent': 'Europe', 'type': 'country', 'code': 204},
    {'name': 'Sao Tome and Principe', 'continent': 'Africa', 'type': 'country', 'code': 205},
    {'name': 'Saudi Arabia', 'continent': 'Asia', 'type': 'country', 'code': 206},
    {'name': 'Senegal', 'continent': 'Africa', 'type': 'country', 'code': 207},
    {'name': 'Serbia', 'continent': 'Europe', 'type': 'country', 'code': 208},
    {'name': 'Seychelles', 'continent': 'Africa', 'type': 'country', 'code': 209},
    {'name': 'Sierra Leone', 'continent': 'Africa', 'type': 'country', 'code': 210},
    {'name': 'Singapore', 'continent': 'Asia', 'type': 'country', 'code': 211},
    {'name': 'Sint Maarten', 'continent': 'Caribbean', 'type': 'country', 'code': 212},
    {'name': 'Slovakia', 'continent': 'Europe', 'type': 'country', 'code': 213},
    {'name': 'Slovenia', 'continent': 'Europe', 'type': 'country', 'code': 214},
    {'name': 'Solomon Islands', 'continent': 'Oceania', 'type': 'country', 'code': 215},
    {'name': 'Somalia', 'continent': 'Africa', 'type': 'country', 'code': 216},
    {'name': 'South Africa', 'continent': 'Africa', 'type': 'country', 'code': 217},
    {'name': 'South Georgia and South Sandwich Islands', 'continent': 'South America', 'type': 'country', 'code': 218},
    {'name': 'South Korea', 'continent': 'Asia', 'type': 'country', 'code': 219},
    {'name': 'South Sudan', 'continent': 'Africa', 'type': 'country', 'code': 220},
    {'name': 'Spain', 'continent': 'Europe', 'type': 'country', 'code': 221},
    {'name': 'Sri Lanka', 'continent': 'Asia', 'type': 'country', 'code': 222},
    {'name': 'Sudan', 'continent': 'Africa', 'type': 'country', 'code': 223},
    {'name': 'Suriname', 'continent': 'South America', 'type': 'country', 'code': 224},
    {'name': 'Svalbard and Jan Mayen', 'continent': 'Europe', 'type': 'country', 'code': 225},
    {'name': 'Eswatini', 'continent': 'Africa', 'type': 'country', 'code': 226},
    {'name': 'Sweden', 'continent': 'Europe', 'type': 'country', 'code': 227},
    {'name': 'Switzerland', 'continent': 'Europe', 'type': 'country', 'code': 228},
    {'name': 'Syria', 'continent': 'Asia', 'type': 'country', 'code': 229},
    {'name': 'Taiwan', 'continent': 'Asia', 'type': 'country', 'code': 230},
    {'name': 'Tajikistan', 'continent': 'Asia', 'type': 'country', 'code': 231},
    {'name': 'Tanzania', 'continent': 'Africa', 'type': 'country', 'code': 232},
    {'name': 'Thailand', 'continent': 'Asia', 'type': 'country', 'code': 233},
    {'name': 'Timor-Leste', 'continent': 'Asia', 'type': 'country', 'code': 234},
    {'name': 'East Timor', 'continent': 'Asia', 'type': 'country', 'code': 234},
    {'name': 'Togo', 'continent': 'Africa', 'type': 'country', 'code': 235},
    {'name': 'Tokelau', 'continent': 'Oceania', 'type': 'country', 'code': 236},
    {'name': 'Tonga', 'continent': 'Oceania', 'type': 'country', 'code': 237},
    {'name': 'Trinidad and Tobago', 'continent': 'Caribbean', 'type': 'country', 'code': 238},
    {'name': 'Tunisia', 'continent': 'Africa', 'type': 'country', 'code': 239},
    {'name': 'Turkey', 'continent': 'Asia', 'type': 'country', 'code': 240},
    {'name': 'Turkmenistan', 'continent': 'Asia', 'type': 'country', 'code': 241},
    {'name': 'Turks and Caicos Islands', 'continent': 'Caribbean', 'type': 'country', 'code': 242},
    {'name': 'Tuvalu', 'continent': 'Oceania', 'type': 'country', 'code': 243},
    {'name': 'Uganda', 'continent': 'Africa', 'type': 'country', 'code': 244},
    {'name': 'Ukraine', 'continent': 'Europe', 'type': 'country', 'code': 245},
    {'name': 'United Arab Emirates', 'continent': 'Asia', 'type': 'country', 'code': 246},
    {'name': 'United Kingdom', 'continent': 'Europe', 'type': 'country', 'code': 247},
    {'name': 'United States', 'continent': 'Northern America', 'type': 'country', 'code': 248},
    {'name': 'Uruguay', 'continent': 'South America', 'type': 'country', 'code': 249},
    {'name': 'Uzbekistan', 'continent': 'Asia', 'type': 'country', 'code': 250},
    {'name': 'Vanuatu', 'continent': 'Oceania', 'type': 'country', 'code': 251},
    {'name': 'Venezuela', 'continent': 'South America', 'type': 'country', 'code': 252},
    {'name': 'Vietnam', 'continent': 'Asia', 'type': 'country', 'code': 253},
    {'name': 'Wallis and Futuna', 'continent': 'Oceania', 'type': 'country', 'code': 254},
    {'name': 'Western Sahara', 'continent': 'Africa', 'type': 'country', 'code': 255},
    {'name': 'Yemen', 'continent': 'Asia', 'type': 'country', 'code': 256},
    {'name': 'Zambia', 'continent': 'Africa', 'type': 'country', 'code': 257},
    {'name': 'Zimbabwe', 'continent': 'Africa', 'type': 'country', 'code': 258},
    {'name': 'Clipperton Island', 'continent': 'Europe', 'type': 'country', 'code': 259},
    {'name': 'Navassa Island', 'continent': 'Caribbean', 'type': 'country', 'code': 260},
    {'name': 'Sint Eustatius', 'continent': 'Caribbean', 'type': 'country', 'code': 261},
    {'name': 'Saba', 'continent': 'Caribbean', 'type': 'country', 'code': 262},
    {'name': 'Vietnam', 'continent': 'Asia', 'type': 'country', 'code': 263},
    {'name': 'South Korea', 'continent': 'Asia', 'type': 'country', 'code': 264},
    {'name': 'Pacific Islands', 'continent': 'Oceania', 'type': 'country', 'code': 265},
    {'name': 'Eswatini', 'continent': 'Africa', 'type': 'country', 'code': 266},
    {'name': 'Sub-Saharan Africa', 'continent': 'Africa', 'type': 'region', 'code': 267}
]